# Writes a header with the commit the build came from.
#
# Runs as a build step, not at configure time: a configure-time value goes
# stale as soon as a commit is made without reconfiguring, and then the About
# box names a build that this binary is not.
#
# Usage: cmake -DOUT=<header path> -DSRC_DIR=<repo root> -P gen_build_info.cmake

execute_process(
    COMMAND git -C "${SRC_DIR}" rev-parse --short HEAD
    OUTPUT_VARIABLE SWEEPCAP_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT SWEEPCAP_COMMIT)
    set(SWEEPCAP_COMMIT "unknown")
endif()

# A trailing "+" marks a working tree that differs from the commit, so the
# hash is never mistaken for exactly that commit's code.
execute_process(
    COMMAND git -C "${SRC_DIR}" status --porcelain --untracked-files=no
    OUTPUT_VARIABLE SWEEPCAP_DIRTY
    ERROR_QUIET
)
if(NOT SWEEPCAP_DIRTY STREQUAL "")
    string(APPEND SWEEPCAP_COMMIT "+")
endif()

set(CONTENT "// Generated by tools/gen_build_info.cmake. Do not edit.
#ifndef SWEEPCAP_BUILD_INFO_H
#define SWEEPCAP_BUILD_INFO_H
#define SWEEPCAP_COMMIT   \"${SWEEPCAP_COMMIT}\"
#define SWEEPCAP_COMMIT_W L\"${SWEEPCAP_COMMIT}\"
#endif
")

# Write only on change, so an unchanged hash does not recompile its includers
# on every build.
if(EXISTS "${OUT}")
    file(READ "${OUT}" EXISTING)
else()
    set(EXISTING "")
endif()
if(NOT EXISTING STREQUAL CONTENT)
    file(WRITE "${OUT}" "${CONTENT}")
endif()
